

### create new Pin:
POST http://localhost:5000/api/pins
Content-Type: application/json

{
    "username":"nadien",
    "title":"test2",
    "description":"bla bla canada",
    "rating":3,
    "lat": 51.340199,
    "lon":12.360103
}

### get all Pins:
GET http://localhost:5000/api/pins


################################
### create new User:
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "username":"test2",
    "email":"test2@mail.com",
    "password":"12345"
}


### user login:
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username":"test1",
    "password":"123456"
}